// Board generation — three-pool stratified ("H8") model.
//
// Each board draws an exact count from three pools (vowels, backbone
// consonants, others), then shuffles. Pool weights are per-size and were
// derived once from the historical Boggle dice, then tuned via grid search
// against a metrics suite (common-word count, length-6+ count, coverage,
// concentration). See scripts/calibrate-letters.ts and scripts/tune-quotas.ts
// for the calibration harness and search procedure.
//
// Pinning per-board V/B counts is what closes the variance gap vs the dice
// on right-skewed metrics — same-mean IID has wider per-board distribution
// and therefore a lower median on common-word count.

import { Board } from 'models';
import { mulberry32 } from 'models/seedCode';

type Weights = Record<string, number>;

interface SizeConfig {
  vowel: Weights;
  backbone: Weights;
  other: Weights;
  V: number;  // exact vowel count per board
  B: number;  // exact backbone count per board (O = size² - V - B)
}

// Generated by scripts/dump-engine-config.ts from the historical Boggle dice.
// Bare Q faces are merged into Qu (the 2-letter tile we always emit).
const SIZE_CONFIG: Record<number, SizeConfig> = {
  4: {
    vowel:    { A: 6, E: 9, I: 7, O: 3, U: 3 },
    backbone: { D: 6, L: 8, N: 6, R: 5, S: 6, T: 4 },
    other:    { B: 2, C: 5, F: 2, G: 3, H: 3, K: 2, M: 3, P: 5, Qu: 2, V: 1, Y: 3, Z: 2 },
    V: 5, B: 7,
  },
  5: {
    vowel:    { A: 12, E: 19, I: 11, O: 11, U: 4 },
    backbone: { D: 6, L: 5, N: 11, R: 12, S: 9, T: 13 },
    other:    { B: 1, C: 5, F: 4, G: 3, H: 5, J: 1, K: 1, M: 4, P: 4, Qu: 1, V: 1, W: 2, X: 1, Y: 3, Z: 1 },
    V: 10, B: 9,
  },
  6: {
    vowel:    { A: 16, E: 28, I: 15, O: 18, U: 7 },
    backbone: { D: 9, L: 9, N: 17, R: 12, S: 15, T: 17 },
    other:    { B: 2, C: 7, F: 5, G: 4, H: 9, J: 1, K: 1, M: 5, P: 5, Qu: 3, V: 2, W: 3, X: 1, Y: 4, Z: 1 },
    V: 13, B: 14,
  },
};

type Cdf = Array<[string, number]>;

function buildCdf(weights: Weights): Cdf {
  const entries = Object.entries(weights).filter(([, w]) => w > 0);
  const total = entries.reduce((s, [, w]) => s + w, 0);
  const cdf: Cdf = [];
  let acc = 0;
  for (const [letter, w] of entries) {
    acc += w / total;
    cdf.push([letter, acc]);
  }
  return cdf;
}

function sample(cdf: Cdf, rng: () => number): string {
  const r = rng();
  for (const [letter, c] of cdf) if (r < c) return letter;
  return cdf[cdf.length - 1][0];
}

function generateBoardCore(size: number, rng: () => number): Board {
  const cfg = SIZE_CONFIG[size] ?? SIZE_CONFIG[4];
  const vCdf = buildCdf(cfg.vowel);
  const bCdf = buildCdf(cfg.backbone);
  const oCdf = buildCdf(cfg.other);
  const total = size * size;

  const cells: string[] = [];
  for (let i = 0; i < cfg.V; i++) cells.push(sample(vCdf, rng));
  for (let i = 0; i < cfg.B; i++) cells.push(sample(bCdf, rng));
  for (let i = cfg.V + cfg.B; i < total; i++) cells.push(sample(oCdf, rng));

  for (let i = cells.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [cells[i], cells[j]] = [cells[j], cells[i]];
  }

  const board: Board = [];
  for (let r = 0; r < size; r++) board.push(cells.slice(r * size, (r + 1) * size));
  return board;
}

export function generateBoard(size: number = 4): Board {
  return generateBoardCore(size, Math.random);
}

export function generateSeededBoard(size: number, seed: number): Board {
  return generateBoardCore(size, mulberry32(seed));
}
