// Computes the per-size H8 letter weights from the predecessor dice arrays
// and emits TypeScript-ready constants. Run once to seed engine/board.ts
// with the production H8 config; after that, the dice arrays are deleted
// and these computed constants are the only source of truth.

const DICE_BY_SIZE: Record<number, string[][]> = {
  4: [
    ['A','A','F','K','P','S'], ['A','A','E','E','G','N'], ['A','V','I','D','Y','N'],
    ['C','M','P','F','E','D'], ['I','C','N','S','S','P'], ['D','R','L','G','E','U'],
    ['P','C','K','H','D','Qu'], ['B','U','E','C','L','S'], ['E','M','N','I','Q','Z'],
    ['B','G','L','E','N','Y'], ['O','U','T','E','S','P'], ['A','H','M','O','C','S'],
    ['T','I','I','L','Z','R'], ['R','D','E','L','L','O'], ['H','N','I','R','T','L'],
    ['I','D','R','T','Y','L'],
  ],
  5: [
    ['A','A','A','F','R','S'], ['A','A','E','E','E','E'], ['A','A','F','I','R','S'],
    ['A','D','E','N','N','N'], ['A','E','E','E','E','M'], ['A','E','E','G','M','U'],
    ['A','E','G','M','N','N'], ['A','F','I','R','S','Y'], ['B','J','K','Qu','X','Z'],
    ['C','C','E','N','S','T'], ['C','E','I','I','L','T'], ['C','E','I','L','P','T'],
    ['C','E','I','P','S','T'], ['D','D','H','N','O','T'], ['D','H','H','L','O','R'],
    ['D','H','L','N','O','R'], ['D','H','L','N','O','R'], ['E','I','I','I','T','T'],
    ['E','M','O','T','T','T'], ['E','N','S','S','S','U'], ['F','I','P','R','S','Y'],
    ['G','O','R','R','V','W'], ['I','P','R','R','R','Y'], ['N','O','O','T','U','W'],
    ['O','O','O','T','T','U'],
  ],
  6: [
    ['A','A','A','F','R','S'], ['A','A','E','E','E','E'], ['A','A','E','E','O','O'],
    ['A','A','F','I','R','S'], ['A','B','D','E','I','O'], ['A','D','E','N','N','N'],
    ['A','E','E','E','E','M'], ['A','E','E','G','M','U'], ['A','E','G','M','N','N'],
    ['A','F','I','R','S','Y'], ['A','N','O','T','H','E'], ['B','J','K','Qu','X','Z'],
    ['C','C','E','N','S','T'], ['C','D','D','L','N','N'], ['C','E','I','I','L','T'],
    ['C','E','I','L','P','T'], ['C','E','I','P','S','T'], ['C','F','G','N','U','Y'],
    ['D','D','H','N','O','T'], ['D','H','H','L','O','R'], ['D','H','H','N','O','W'],
    ['D','H','L','N','O','R'], ['E','H','I','L','R','S'], ['E','I','I','L','S','T'],
    ['E','I','L','P','S','T'], ['E','I','O','Qu','U','V'], ['E','M','O','T','T','T'],
    ['E','N','S','S','S','U'], ['F','I','P','R','S','Y'], ['G','O','R','R','V','W'],
    ['H','I','P','R','R','Y'], ['I','N','Qu','U','M','N'], ['L','E','E','S','T','R'],
    ['N','O','O','T','U','W'], ['O','O','O','T','T','U'], ['O','S','S','O','T','T'],
  ],
};

const VOWELS = new Set(['A','E','I','O','U']);
const BACKBONES = new Set(['T','S','R','N','L','D']);

const QUOTAS: Record<number, { V: number; B: number }> = {
  4: { V: 5, B: 7 },
  5: { V: 10, B: 9 },
  6: { V: 13, B: 14 },
};

function categorize(faces: string[][]): { vowel: Record<string, number>; backbone: Record<string, number>; other: Record<string, number> } {
  const v: Record<string, number> = {};
  const b: Record<string, number> = {};
  const o: Record<string, number> = {};
  for (const die of faces) {
    for (const face of die) {
      // Merge bare Q faces into Qu — matches the calibration script's sampler
      // (Q → Qu), so the engine's per-cell Qu rate equals what we measured.
      const tile = face === 'Q' ? 'Qu' : face;
      const bag = VOWELS.has(tile) ? v : BACKBONES.has(tile) ? b : o;
      bag[tile] = (bag[tile] ?? 0) + 1;
    }
  }
  return { vowel: v, backbone: b, other: o };
}

// Format a weights record on a single line, sorted by letter for stability.
function fmt(weights: Record<string, number>): string {
  const entries = Object.entries(weights).sort(([a], [b]) => a.localeCompare(b));
  return '{ ' + entries.map(([l, w]) => `${l}: ${w}`).join(', ') + ' }';
}

console.log('// Generated by scripts/dump-engine-config.ts. Per-size H8 letter weights');
console.log('// derived from the predecessor dice arrays. After this file is checked');
console.log('// in, the dice arrays themselves are no longer kept anywhere in the repo.');
console.log('');
console.log('const SIZE_CONFIG: Record<number, { vowel: Weights; backbone: Weights; other: Weights; V: number; B: number }> = {');
for (const size of [4, 5, 6]) {
  const { vowel, backbone, other } = categorize(DICE_BY_SIZE[size]);
  const { V, B } = QUOTAS[size];
  console.log(`  ${size}: {`);
  console.log(`    vowel:    ${fmt(vowel)},`);
  console.log(`    backbone: ${fmt(backbone)},`);
  console.log(`    other:    ${fmt(other)},`);
  console.log(`    V: ${V}, B: ${B},`);
  console.log(`  },`);
}
console.log('};');
